### ISSUE TITLE
Master Issue

### ISSUE THREAD

**Issue by mhsjlw** [mhsjlw/mcpelauncher#1]
- [x] Keyboard controls
- [x] Mouse sensitivity
- [ ] Paste
- [x] Stack corruption when loading worlds
- [x] Worlds are not saved
- [x] Instructions for installation
...

And when that's all done, let's get this merged upstream!
